"""
Script to detect SynthID watermarks in images using Google's SynthID API.

This script attempts to use Vertex AI Imagen API or Google AI SDK to detect
SynthID watermarks embedded in images.

python synthid_detection.py --method gemini real.webp
"""

import base64
import os
import re
from pathlib import Path
from typing import Any, Dict, Optional

from google import genai

from core.schemas import StepResult, TaskInput
from steps.base import BaseStep

# Optional: Uncomment if using Vertex AI
# from google.cloud import aiplatform


def read_image_bytes(image_path: str) -> bytes:
    """
    Read image file as bytes.

    Args:
        image_path: Path to the image file

    Returns:
        Image file as bytes
    """
    with open(image_path, 'rb') as image_file:
        return image_file.read()


def detect_synthid_watermark_vertex_ai(
    image_path: str,
    project_id: Optional[str] = None,
    location: str = "us-central1"
) -> Dict[str, Any]:
    """
    Detect SynthID watermark using Vertex AI Imagen API.

    Note: This requires google-cloud-aiplatform package and proper GCP setup.
    The actual SynthID detection endpoint may not be publicly available yet.

    Args:
        image_path: Path to the image file to check
        project_id: Google Cloud project ID (defaults to environment variable)
        location: GCP location (default: us-central1)

    Returns:
        Dictionary containing detection results
    """
    try:
        from google.cloud import aiplatform
    except ImportError:
        raise ImportError(
            "google-cloud-aiplatform package not installed. "
            "Install it with: pip install google-cloud-aiplatform"
        )

    if project_id is None:
        project_id = os.getenv("GOOGLE_CLOUD_PROJECT")
        if project_id is None:
            raise ValueError(
                "GOOGLE_CLOUD_PROJECT environment variable not set. "
                "Please set it or provide project_id parameter."
            )

    # Initialize Vertex AI
    aiplatform.init(project=project_id, location=location)

    # Read image
    image_bytes = read_image_bytes(image_path)

    # Prepare the request for SynthID detection
    # Note: This endpoint structure is a placeholder - actual API may differ
    try:
        # Attempt to use Vertex AI endpoint for SynthID detection
        # This is a placeholder structure - actual endpoint may differ
        endpoint = aiplatform.Endpoint(
            endpoint_name=f"projects/{project_id}/locations/{location}/endpoints/synthid-detector"
        )

        instance = {
            "image": {
                "bytes": base64.b64encode(image_bytes).decode('utf-8')
            }
        }

        prediction = endpoint.predict(instances=[instance])

        return {
            "has_watermark": prediction.predictions[0].get("has_watermark", False),
            "confidence": prediction.predictions[0].get("confidence", 0.0),
            "method": "vertex_ai"
        }
    except Exception as e:
        raise Exception(f"Vertex AI detection failed: {str(e)}")


def detect_synthid_watermark_gemini(
    image_path: str,
    api_key: Optional[str] = None,
    model_name: str = "gemini-2.0-flash-exp"
) -> Dict[str, Any]:
    """
    Detect SynthID watermark using Gemini API with image analysis.

    Note: This is a workaround method that uses Gemini to analyze the image.
    For actual SynthID detection, use the Vertex AI method when available.

    Args:
        image_path: Path to the image file to check
        api_key: Google API key (defaults to GOOGLE_API_KEY environment variable)
        model_name: Gemini model name to use

    Returns:
        Dictionary containing detection results
    """
    if api_key is None:
        api_key = os.getenv("GOOGLE_API_KEY")
        if api_key is None:
            raise ValueError(
                "GOOGLE_API_KEY environment variable not set. "
                "Please set it or provide api_key parameter."
            )

    # Create Gemini client
    client = genai.Client(api_key=api_key)

    # Read image
    image_bytes = read_image_bytes(image_path)

    # Create a prompt for SynthID detection
    prompt = """Analyze this image to determine if it contains a SynthID watermark.

SynthID is Google's imperceptible watermarking technology for AI-generated images.
Please check if this image appears to have been generated by AI and might contain a SynthID watermark.

Respond with:
1. Whether the image likely contains a SynthID watermark (yes/no)
2. Your confidence level (0.0 to 1.0)
3. Brief reasoning

Format your response as:
WATERMARK: yes/no
CONFIDENCE: 0.0-1.0
REASONING: [brief explanation]
"""

    try:
        # Determine MIME type from file extension
        image_ext = Path(image_path).suffix.lower()
        mime_types = {
            '.jpg': 'image/jpeg',
            '.jpeg': 'image/jpeg',
            '.png': 'image/png',
            '.webp': 'image/webp',
            '.gif': 'image/gif'
        }
        mime_type = mime_types.get(image_ext, 'image/jpeg')

        # Encode image to base64
        image_base64 = base64.b64encode(image_bytes).decode('utf-8')

        # Use Gemini API to analyze the image
        # The google-genai SDK expects contents as a list with parts
        # Each part can be text or an image (as a dict with inline_data)
        response = client.models.generate_content(
            model=model_name,
            contents=[
                {
                    "parts": [
                        {"text": prompt},
                        {
                            "inline_data": {
                                "mime_type": mime_type,
                                "data": image_base64
                            }
                        }
                    ]
                }
            ]
        )

        # Parse response
        response_text = response.text

        # Extract watermark detection from response
        # Convert to lowercase for case-insensitive matching
        response_lower = response_text.lower()
        has_watermark = "watermark: yes" in response_lower
        confidence = 0.5  # Default confidence

        # Try to extract confidence value
        confidence_match = re.search(r"CONFIDENCE:\s*([0-9.]+)", response_text, re.IGNORECASE)
        if confidence_match:
            confidence = float(confidence_match.group(1))

        return {
            "has_watermark": has_watermark,
            "confidence": confidence,
            "method": "gemini_analysis",
            "raw_response": response_text
        }
    except Exception as e:
        raise Exception(f"Gemini detection failed: {str(e)}")


def detect_synthid_watermark(
    image_path: str,
    method: str = "auto",
    api_key: Optional[str] = None,
    project_id: Optional[str] = None
) -> Dict[str, Any]:
    """
    Main function to detect SynthID watermark in an image.

    Args:
        image_path: Path to the image file to check
        method: Detection method - "auto", "vertex_ai", or "gemini"
        api_key: Google API key (defaults to GOOGLE_API_KEY env var)
        project_id: Google Cloud project ID (for Vertex AI method)

    Returns:
        Dictionary containing detection results with keys:
        - has_watermark: Boolean indicating if watermark was detected
        - confidence: Float between 0.0 and 1.0
        - method: String indicating which method was used
    """
    if not os.path.exists(image_path):
        raise FileNotFoundError(f"Image file not found: {image_path}")

    # Get API key from parameter or environment variable
    if api_key is None:
        api_key = os.getenv("GOOGLE_API_KEY")

    if method == "auto":
        # Try Vertex AI first, fall back to Gemini
        try:
            return detect_synthid_watermark_vertex_ai(image_path, project_id)
        except Exception as e:
            print(f"Vertex AI method failed: {e}")
            print("Falling back to Gemini method...")
            return detect_synthid_watermark_gemini(image_path, api_key)
    elif method == "vertex_ai":
        return detect_synthid_watermark_vertex_ai(image_path, project_id)
    elif method == "gemini":
        return detect_synthid_watermark_gemini(image_path, api_key)
    else:
        raise ValueError(f"Unknown method: {method}. Use 'auto', 'vertex_ai', or 'gemini'.")


class SynthIDDetection(BaseStep):
    def run(self, input_data: TaskInput) -> StepResult:
        # PUT YOUR LOGIC IN HERE
        print(f"  [Tool4] Detecting SynthID watermark in {input_data.image_path}...")
        
        try:
            # Use the detect_synthid_watermark function with auto method
            result = detect_synthid_watermark(
                input_data.image_path,
                method="auto"
            )
            
            return StepResult(
                source="SynthIDDetection",
                content={
                    "has_watermark": result.get("has_watermark", False),
                    "confidence": result.get("confidence", 0.0),
                    "method": result.get("method", "unknown"),
                    "raw_response": result.get("raw_response", None)
                }
            )
        except Exception as e:
            return StepResult(
                source="SynthIDDetection",
                content={
                    "error": f"Error detecting SynthID watermark: {str(e)}"
                }
            )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Detect SynthID watermarks in images using Google's SynthID API"
    )
    parser.add_argument(
        "image_path",
        type=str,
        help="Path to the image file to check for watermarks"
    )
    parser.add_argument(
        "--method",
        type=str,
        choices=["auto", "vertex_ai", "gemini"],
        default="auto",
        help="Detection method to use (default: auto)"
    )
    parser.add_argument(
        "--api-key",
        type=str,
        default=None,
        help="Google API key (or set GOOGLE_API_KEY env var)"
    )
    parser.add_argument(
        "--project-id",
        type=str,
        default=None,
        help="Google Cloud project ID (or set GOOGLE_CLOUD_PROJECT env var)"
    )

    args = parser.parse_args()

    # Get API key from argument or environment variable
    api_key = args.api_key or os.getenv("GOOGLE_API_KEY")

    print(f"Checking image: {args.image_path}")
    print(f"Method: {args.method}")
    print("-" * 50)

    try:
        result = detect_synthid_watermark(
            args.image_path,
            method=args.method,
            api_key=api_key,
            project_id=args.project_id
        )

        print("\nDetection Results:")
        print(f"  Has Watermark: {result['has_watermark']}")
        print(f"  Confidence: {result['confidence']:.2f}")
        print(f"  Method Used: {result['method']}")

        if 'raw_response' in result:
            print(f"\n  Raw Response:\n  {result['raw_response']}")

        print("\n" + "=" * 50)

        # Exit with appropriate code
        exit(0 if result['has_watermark'] else 1)

    except Exception as e:
        print(f"Error: {e}")
        exit(1)
